# Allow issues to be created without a template
blank_issues_enabled: true

contact_links:
  - name: Report a security vulnerability
    about: Please do not file an issue and instead email security@webrecorder.org. We will follow up with you there!
    url: mailto:security@webrecorder.org
  - name: Get help on our forum
    url: https://forum.webrecorder.net/
    about: Have a ("how do I...?") question? Not sure if your issue is reproducible? The best way to get help is on our community forum!
