name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up corepack
        run: corepack enable yarn

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --immutable

      - name: Yarn Lint
        run: yarn lint
