name: Build + Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Yarn Lint
        run: yarn run lint

      - name: Yarn Build
        run: yarn run build
